# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uncles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'First')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Last')),
            ],
            options={
                'verbose_name': 'Uncle',
                'verbose_name_plural': 'Uncles',
            },
        ),
    ]
