# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20151214_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='city',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name=b'City'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='iso',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name=b'Country'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='postalcode',
            field=models.CharField(blank=True, max_length=20, verbose_name=b'Postal Code'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='province',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name=b'Province'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='street',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name=b'street'),
        ),
    ]
