# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20151214_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='street',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Street'),
        ),
    ]
