# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20151214_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name=b'latitude'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name=b'longitude'),
        ),
    ]
