# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20151214_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waittime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('waittime', models.IntegerField(blank=True, help_text=b'Wait time in seconds.', null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waittime_set', to='restaurant.Restaurants')),
            ],
        ),
    ]
