# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_waittime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='slug',
            field=models.CharField(blank=True, help_text=b"Used for automatically generating URLs like '/us/texas/austin/shop-name'.", max_length=140, null=True, verbose_name=b'Slug'),
        ),
    ]
